services:
  node:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    command: sh -c "npm install -g @google/gemini-cli && npm install && tail -f /dev/null"
    stdin_open: true
    tty: true

volumes:
  node_modules:
